# Snapshot report for `test/level.js`

The actual snapshot is saved in `level.js.snap`.

Generated by [AVA](https://ava.li).

## [multipleResolves] should emit a warning when opts.level() uses an invalid level

> Snapshot 1

    `[33m[7m[1m ‚ö†  warning [22m[27m Warning: Invalid option 'level.multipleResolves' returning 'invalid': function must return undefined or one of debug, info, warn, error, silent[39m‚êä
    [2m        at emitWarning (/home/ether/code/log-process-errors/src/level.js:28:3)[22m‚êä
    [2m        at validateLevel (/home/ether/code/log-process-errors/src/level.js:18:3)[22m‚êä
    [2m        at getLevel (/home/ether/code/log-process-errors/src/handle.js:46:17)[22m‚êä
    [2m        at Generator.next (<anonymous>)[22m‚êä
    [2m        at asyncGeneratorStep (/home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)[22m‚êä
    [2m        at _next (/home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)[22m‚êä
    [2m        at /home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7[22m‚êä
    [2m        at new Promise (<anonymous>)[22m‚êä
    [2m        at /home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12[22m‚êä
    [2m        at logEvent (/home/ether/code/log-process-errors/src/handle.js:45:15)[22m`

## [rejectionHandled] should emit a warning when opts.level() uses an invalid level

> Snapshot 1

    `[33m[7m[1m ‚ö†  warning [22m[27m Warning: Invalid option 'level.rejectionHandled' returning 'invalid': function must return undefined or one of debug, info, warn, error, silent[39m‚êä
    [2m        at emitWarning (/home/ether/code/log-process-errors/src/level.js:28:3)[22m‚êä
    [2m        at validateLevel (/home/ether/code/log-process-errors/src/level.js:18:3)[22m‚êä
    [2m        at getLevel (/home/ether/code/log-process-errors/src/handle.js:46:17)[22m‚êä
    [2m        at Generator.next (<anonymous>)[22m‚êä
    [2m        at asyncGeneratorStep (/home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)[22m‚êä
    [2m        at _next (/home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)[22m‚êä
    [2m        at /home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7[22m‚êä
    [2m        at new Promise (<anonymous>)[22m‚êä
    [2m        at /home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12[22m‚êä
    [2m        at logEvent (/home/ether/code/log-process-errors/src/handle.js:45:15)[22m`

## [uncaughtException] should emit a warning when opts.level() uses an invalid level

> Snapshot 1

    `[33m[7m[1m ‚ö†  warning [22m[27m Warning: Invalid option 'level.uncaughtException' returning 'invalid': function must return undefined or one of debug, info, warn, error, silent[39m‚êä
    [2m        at emitWarning (/home/ether/code/log-process-errors/src/level.js:28:3)[22m‚êä
    [2m        at validateLevel (/home/ether/code/log-process-errors/src/level.js:18:3)[22m‚êä
    [2m        at getLevel (/home/ether/code/log-process-errors/src/handle.js:46:17)[22m‚êä
    [2m        at Generator.next (<anonymous>)[22m‚êä
    [2m        at asyncGeneratorStep (/home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)[22m‚êä
    [2m        at _next (/home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)[22m‚êä
    [2m        at /home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7[22m‚êä
    [2m        at new Promise (<anonymous>)[22m‚êä
    [2m        at /home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12[22m‚êä
    [2m        at logEvent (/home/ether/code/log-process-errors/src/handle.js:45:15)[22m`

## [unhandledRejection] should emit a warning when opts.level() uses an invalid level

> Snapshot 1

    `[33m[7m[1m ‚ö†  warning [22m[27m Warning: Invalid option 'level.unhandledRejection' returning 'invalid': function must return undefined or one of debug, info, warn, error, silent[39m‚êä
    [2m        at emitWarning (/home/ether/code/log-process-errors/src/level.js:28:3)[22m‚êä
    [2m        at validateLevel (/home/ether/code/log-process-errors/src/level.js:18:3)[22m‚êä
    [2m        at getLevel (/home/ether/code/log-process-errors/src/handle.js:46:17)[22m‚êä
    [2m        at Generator.next (<anonymous>)[22m‚êä
    [2m        at asyncGeneratorStep (/home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)[22m‚êä
    [2m        at _next (/home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)[22m‚êä
    [2m        at /home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7[22m‚êä
    [2m        at new Promise (<anonymous>)[22m‚êä
    [2m        at /home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12[22m‚êä
    [2m        at logEvent (/home/ether/code/log-process-errors/src/handle.js:45:15)[22m`

## [warning] should emit a warning when opts.level() uses an invalid level

> Snapshot 1

    `[33m[7m[1m ‚ö†  warning [22m[27m Warning: Invalid option 'level.warning' returning 'invalid': function must return undefined or one of debug, info, warn, error, silent[39m‚êä
    [2m        at emitWarning (/home/ether/code/log-process-errors/src/level.js:28:3)[22m‚êä
    [2m        at validateLevel (/home/ether/code/log-process-errors/src/level.js:18:3)[22m‚êä
    [2m        at getLevel (/home/ether/code/log-process-errors/src/handle.js:46:17)[22m‚êä
    [2m        at Generator.next (<anonymous>)[22m‚êä
    [2m        at asyncGeneratorStep (/home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)[22m‚êä
    [2m        at _next (/home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)[22m‚êä
    [2m        at /home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7[22m‚êä
    [2m        at new Promise (<anonymous>)[22m‚êä
    [2m        at /home/ether/code/log-process-errors/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12[22m‚êä
    [2m        at logEvent (/home/ether/code/log-process-errors/src/handle.js:45:15)[22m`
